version: '3.7'
services:
    mongo:
        image: mongo:latest
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: 'admin'
            MONGO_INITDB_ROOT_PASSWORD: 'password'
            MONGO_INITDB_DATABASE: 'admin'
        ports:
            - 27017:27017
        volumes:
            - ./data:/data/db